# Generated by Django 3.2.11 on 2022-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Web', 'Web Development'), ('Desktop', 'Desktop App Development')], max_length=7)),
                ('client', models.CharField(max_length=20)),
                ('project_date', models.DateField()),
                ('project_url', models.URLField()),
            ],
        ),
    ]
