# Generated by Django 3.2.11 on 2022-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221031_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image_1',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_2',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_3',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
    ]
