# Generated by Django 3.2.11 on 2023-11-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contat Us Page'},
        ),
    ]
