# Generated by Django 3.2.11 on 2023-11-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_contactus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contact_number',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
